/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals.stockx;

import org.junit.Test;
import static org.junit.Assert.*;

public class StockxTest {
    @Test public void appHasAGreeting() {
        Stockx classUnderTest = new Stockx();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
